### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by bkaradzic** [ollix/moui#1]
Can you add some screenshots of apps made with Moui so that I can reference it in projects that are using bgfx?

**Comment by olliwang** [comment]
@bkaradzic I create Moui mainly for my app Fog of World (https://fogofworld.com). Unfortunately, the app currently uses the original NanoVg backend because I encounter several issues when adopting the bgfx backend, one is mentioned in https://github.com/bkaradzic/bgfx/issues/1139. I hope to take advantage of bgfx for switching from OpenGL to Metal to gain some performance but there are some issues needed to be resolved first.
